### ISSUE TITLE
Are you time tracking? 

### ISSUE THREAD

**Issue by ofou** [AstroMatt/book-python#13]
I wonder why you use hashtags like [#time 1m](https://github.com/AstroMatt/book-python/commit/6056deca74909b29f5441265f5df89873c829f26) in the title of every commit. Are you time tracking with any tools, I'd love to use that as well, seems awesome to track time per commit in a more direct way.

**Comment by AstroMatt** [comment]
Yes, I am doing time tracking.

```sh
$ git log --oneline
47c6799c (HEAD -> main, origin/master, origin/main, origin/HEAD) Intermediate: Requirements update #time 2m
5a0b30d3 Intermediate: Types #time 20m
29ceae00 Intermediate: Types #time 20m
a8722838 Intermediate: Types #time 20m
0a1644f1 Intermediate: Types #time 20m
ae701dbb Intermediate: Types #time 120m
13fd774e Intermediate: Unpacking #time 10m
2ac2e20e Advanced: OOP #time 30m
27f562d3 Advanced: OOP #time 10m
0788ac22 Advanced: OOP #time 10m
...
```

```sh
$ git log --oneline |python -c "import sys; hours=sum(int(line.strip().split('#time ')[-1].removesuffix('m')) / 60 for line in sys.stdin); print(round(hours, 2), 'h')"
3113.93 h
```

Please check also a topic of "smart commits" for Jira or Git Lab.
https://dev.astrotech.io/jira/end-user/automation.html#smart-commits
