### ISSUE TITLE
Dekoratory, omyłka?

### ISSUE THREAD

**Issue by antonitomaszewski** [AstroMatt/book-python#9]
[https://github.com/AstroMatt/book-python/blob/master/advanced/decorators/decorator-arguments.rst](url)
Hej, czy w drugiej ramce, nie powinno być `myfunction = mydecorator(a, b)(myfunction)` zamiast `mydecorator = mydecorator(a, b)(myfunction)`
btw naprawdę fajna książka, i przykłady, wielkie wielkie gratki,
Pozdrawiam AT

**Comment by AstroMatt** [comment]
Poprawione.
https://python.astrotech.io/advanced/decorators/decorator-arguments.html

Dziękuję Ci bardzo!

PS. W nadchodzącym tygodniu będę miał 5 dni full-time na poprawę rozdziału Advanced.
Dojdzie wiele nowych przykładów, te które już są zostaną poprawione.
A i wpadnie trochę nowych zadań.
